services:
  - type: web
    name: Cozy Weather Bot
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    healthCheckPath: /
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: WINDY_WEBCAMS_API_KEY
        sync: false
      - key: WINDY_PLUGIN_API_KEY
        sync: false
      - key: WINDY_MAP_FORECAST_API_KEY
        sync: false
      - key: WINDY_POINT_FORECAST_API_KEY
        sync: false
      - key: GROK_API_KEY
        sync: false





